# Generated by Django 5.2 on 2025-04-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('camisa', 'Camisa'), ('pantalon', 'Pantalon'), ('falda', 'Falda'), ('saco', 'Saco'), ('zapatos', 'Zapatos'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
